### ISSUE TITLE
Error formatting document

### ISSUE THREAD

**Issue by rbluethl** [tailwindlabs/prettier-plugin-tailwindcss#11]
Hey there! I'm getting this error in the VS code output console when trying to format a rather large .vue file. (SFC with `script setup`). I tried a bunch of files and this one isn't formatting properly, all others work super smooth. I can't share the exact file but I can provide some more details if necessary.

`prettier` version: 2.5.1
`prettier-plugin-tailwindcss` version: 0.1.3
`tailwindcss` version: 3.0.16

```
["ERROR" - 8:15:05 AM] Error formatting document.
TypeError: Cannot read property 'includes' of null
    at Lr (/Users/.../node_modules/prettier-plugin-tailwindcss/dist/index.js:145:943)
    at n (/Users/.../node_modules/prettier-plugin-tailwindcss/dist/index.js:145:2520)
    at n (/Users/.../node_modules/prettier-plugin-tailwindcss/dist/index.js:145:2956)
    at n (/Users/.../node_modules/prettier-plugin-tailwindcss/dist/index.js:145:2956)
    at n (/Users/.../node_modules/prettier-plugin-tailwindcss/dist/index.js:145:2956)
    at n (/Users/.../node_modules/prettier-plugin-tailwindcss/dist/index.js:145:2956)
    at Object.parse (/Users/.../node_modules/prettier-plugin-tailwindcss/dist/index.js:145:2363)
    at Object.parse$d [as parse] (/Users/.../node_modules/prettier/index.js:12975:19)
    at coreFormat (/Users/.../node_modules/prettier/index.js:14525:16)
    at formatWithCursor$1 (/Users/.../node_modules/prettier/index.js:14765:14)
    at /Users/.../node_modules/prettier/index.js:60959:12
    at Object.Success [as format] (/Users/.../node_modules/prettier/index.js:60979:12)
    at t.default.<anonymous> (/Users/.../.vscode/extensions/esbenp.prettier-vscode-9.1.0/src/PrettierEditService.ts:435:45)
    at Generator.next (<anonymous>)
    at s (/Users/.../.vscode/extensions/esbenp.prettier-vscode-9.1.0/dist/extension.js:1:7872)
```

**Comment by reinink** [comment]
@rbluethl Are you able to provide the full source code of the file in question so that we're able to reproduce this?

**Comment by rbluethl** [comment]
@reinink sure - sent you an email! Thanks for looking into it.

**Comment by reinink** [comment]
@rbluethl Got it, thanks 👍

**Comment by bradlc** [comment]
Hey @rbluethl. I was able to reproduce the error you were seeing by using an empty class attribute (e.g. `<div class>`), and this has been fixed in `v0.1.4` 👍 Thanks for reporting!

**Comment by rbluethl** [comment]
Hey @bradlc! That's nice - thank you very much! Just updated to 1.0.4 and noticed that my file is still not formatting. I digged a bit and found that this expression: `:class="getPayableFolioAmount(item.folios![0].id!) > 0 ? 'text-red-700' : 'text-gray-900'"` causes the formatter to fail.

**Comment by bradlc** [comment]
@rbluethl Are you certain that you're on `0.1.4`? You may need to run the `Developer: Restart Extension Host` command in VS Code to get the Prettier extension to pick up the new version

**Comment by rbluethl** [comment]
Ah, snap! That was it... sorry for that! Thank you for the awesome plugin & quick help/fix! 👍
