### ISSUE TITLE
NextJS dev and build mismatch

### ISSUE THREAD

**Issue by milanbgd011** [tailwindlabs/prettier-plugin-tailwindcss#19]
What I did?
- installed package (latest tailwind installed)
- restarted server with `npm run dev`
- entered couple of files and hit save
- reformatting worked

What was the problem?
- when I tried to do `npm run build` I got a lot of ESLint errors caused by prettier
- all errors suggested that the order is different than it should be
- I tried to delete .next dir, reinstall all and try to build again and still the problem remains
- vs code reported no errors in those files, they were reformatted properly, but build complained

Installed packages:
```
"eslint": "8.7.0",
"eslint-config-airbnb": "19.0.4",
"eslint-config-next": "12.0.8",
"eslint-config-prettier": "8.3.0",
"eslint-plugin-import": "2.25.4",
"eslint-plugin-jsx-a11y": "6.5.1",
"eslint-plugin-prettier": "4.0.0",
"eslint-plugin-react": "7.28.0",
"eslint-plugin-react-hooks": "4.3.0",
"autoprefixer": "10.4.2",
"postcss": "8.4.5",
"prettier": "^2.5.1",
"prettier-eslint": "13.0.0",
"prettier-plugin-tailwindcss": "^0.1.4",
"tailwindcss": "3.0.16",
```

![Screenshot 2022-01-25 at 21 03 23](https://user-images.githubusercontent.com/20988958/151051064-b2bb4d8c-2ee5-4b42-b004-5f28a95b9386.png)

**Comment by brianlovin** [comment]
I've started encountering this as well:

<img width="1041" alt="Screen Shot 2022-01-27 at 21 28 29@2x" src="https://user-images.githubusercontent.com/1923260/151492369-129c8967-d134-47cf-ade8-4963e706029b.png">

In [this PR](https://github.com/brianlovin/briOS/pull/1945), my initial Vercel deploy failed, so I uninstalled this package and committed, then the next build completed successfully.

Could this be conflicting with the VSCode extension for intellisense in some way?

**Comment by bradlc** [comment]
Hey @milanbgd011. Please could you share your ESLint config?

@brianlovin, I'm not sure this is the same issue. The errors you are seeing there look correct to me, for example `h-*` should be before `w-*`. So I think your issue is maybe that Prettier/prettier-plugin-tailwindcss is not running locally? Are you using "format on save" on VS Code?

**Comment by kalinicm** [comment]
@bradlc sure, here it is:

```
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "plugins": [ "@typescript-eslint", "prettier"],
  "extends": [
    "next/core-web-vitals",
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "airbnb",
    "prettier"
  ],
  "env": {
    "browser": true,
    "node": true,
    "jquery": true
  },
  "rules": {
    "@typescript-eslint/no-use-before-define": 0,
    "@typescript-eslint/no-explicit-any": 0,
    "@typescript-eslint/no-empty-function": 0,
    "@typescript-eslint/ban-types": 0,
    "@typescript-eslint/ban-ts-comment": 0,
    "@typescript-eslint/no-var-requires": 0,
    "consistent-return": 0,
    "global-require": 0,
    "import/extensions": 0,
    "import/prefer-default-export": 0,
    "jsx-a11y/href-no-hash": 0,
    "no-underscore-dangle": 0,
    "object-curly-spacing": ["error", "always"],
    "react/require-default-props": 0,
    "react/jsx-filename-extension": 0,
    "react/no-danger": 0,
    "react-hooks/exhaustive-deps": 0, 
    "no-restricted-syntax": [0, "ForOfStatement"],
    "no-await-in-loop": 0,
    "import/no-named-as-default": 0,
    "import/named": 0,
    "import/no-unresolved": "off",
    "import/no-cycle": 0,
    "camelcase": 0,
    "no-nested-ternary": 0,
    "no-unused-vars": 1,
    "react/jsx-props-no-spreading": 0,
    "react/destructuring-assignment": 0,
    "no-use-before-define": "off",
    "no-param-reassign": ["error", { "props": true, "ignorePropertyModificationsFor": ["cx", "cxs"] }], // xstate/immer context assign named as c is allowed
    // nextjs stuff
    "@next/next/no-img-element": 0, // I can use <img> element without warning
    "@next/next/no-html-link-for-pages": 0, // do not error on <a> element with href attribute
    "react/jsx-no-useless-fragment": 0,
    "react/function-component-definition": 0,
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true,
        "semi": true,
        "trailingComma": "all",
        "printWidth": 120
      }
    ]
  }
}

```

**Comment by milanbgd011** [comment]
@bradlc sure, here it is:

```json
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "plugins": [ "@typescript-eslint", "prettier"],
  "extends": [
    "next/core-web-vitals",
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "airbnb",
    "prettier"
  ],
  "env": {
    "browser": true,
    "node": true,
    "jquery": true
  },
  "rules": {
    "@typescript-eslint/no-use-before-define": 0,
    "@typescript-eslint/no-explicit-any": 0,
    "@typescript-eslint/no-empty-function": 0,
    "@typescript-eslint/ban-types": 0,
    "@typescript-eslint/ban-ts-comment": 0,
    "@typescript-eslint/no-var-requires": 0,
    "consistent-return": 0,
    "global-require": 0,
    "import/extensions": 0,
    "import/prefer-default-export": 0,
    "jsx-a11y/href-no-hash": 0,
    "no-underscore-dangle": 0,
    "object-curly-spacing": ["error", "always"],
    "react/require-default-props": 0,
    "react/jsx-filename-extension": 0,
    "react/no-danger": 0,
    "react-hooks/exhaustive-deps": 0, 
    "no-restricted-syntax": [0, "ForOfStatement"],
    "no-await-in-loop": 0,
    "import/no-named-as-default": 0,
    "import/named": 0,
    "import/no-unresolved": "off",
    "import/no-cycle": 0,
    "camelcase": 0,
    "no-nested-ternary": 0,
    "no-unused-vars": 1,
    "react/jsx-props-no-spreading": 0,
    "react/destructuring-assignment": 0,
    "no-use-before-define": "off",
    "no-param-reassign": ["error", { "props": true, "ignorePropertyModificationsFor": ["cx", "cxs"] }], // xstate/immer context assign named as c is allowed
    // nextjs stuff
    "@next/next/no-img-element": 0, // I can use <img> element without warning
    "@next/next/no-html-link-for-pages": 0, // do not error on <a> element with href attribute
    "react/jsx-no-useless-fragment": 0,
    "react/function-component-definition": 0,
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true,
        "semi": true,
        "trailingComma": "all",
        "printWidth": 120
      }
    ]
  }
}

```

**Comment by marceloavf** [comment]
Have the same problem from @brianlovin only on vercel,

Tested multiple times and with different node versions on my machine and cant reproduce it.

**Comment by bradlc** [comment]
Hey @milanbgd011. Since you don't seem to have a Prettier config file, I have a feeling this is related to an issue with config resolution that has been resolved in #62. Please could you upgrade the plugin to `v0.1.8` and let me know if that fixes your issue?

**Comment by bradlc** [comment]
Hey @milanbgd011. I have a feeling this could be related to an issue with config resolution that has been resolved in #62. Please could you upgrade the plugin to `v0.1.8` and let me know if that fixes your issue?

**Comment by milanbgd011** [comment]
@bradlc 

This is also resolved for me. Thank you very much for this!

**Comment by robertwt7** [comment]
I'm still experiencing this today with version `0.5.13` and prettier version `3.2.5` not sure why
