### ISSUE TITLE
Prettier places "!important" before actual class

### ISSUE THREAD

**Issue by inside-web** [tailwindlabs/prettier-plugin-tailwindcss#3]
After automatic class sorting was applied, the following code:

`.facetwp-facet {
    @apply mb-0 !important;
}`

... turned into:

`.facetwp-facet {
    @apply !important mb-0;
}`

which is causing an error.

**Comment by 2ne** [comment]
I am also getting this issue. Not sure why it is closed.

**Before**
`@apply sm:left-1/2 sm:-translate-x-1/2 #{!important};`

**After**
`@apply #{!important} sm:left-1/2 sm:-translate-x-1/2;`

**Comment by bradlc** [comment]
Thanks for reporting! This should be fixed in `v0.1.3` 👍

**Comment by thenaim** [comment]
@bradlc, I am still getting this issue. 

tailwindcss: 3.0.18
prettier-plugin-tailwindcss: 0.1.7

![image](https://user-images.githubusercontent.com/45883683/155844510-7c563c13-c63c-4628-9fe7-a42f2f926ac4.png)

**Comment by dmitryevseev** [comment]
@thenaim Had the same issue, and looked in the source. It explicitly looks for `#{!important}` in the code, no quotes.
